### ISSUE TITLE
Vizualizing Predictions

### ISSUE THREAD

**Issue by asadabbas09** [cherubicXN/anisotropic-scale-junction-detector#2]
Thanks for sharing your code.

How do I process *.asj output file to visualize predictions on an image?

**Comment by asadabbas09** [comment]
I'm trying to implement ASJ code for the past couple of weeks. I'm having some difficulties in estimating SCALE values for branches.

1. For any test image (including images provided with code), both ASJ and ACJ have same scale values. e.g. for Junction 1, I get scale=23 in both cases.
2. Estimated scales are always very small.

I've attached asj and acj values and resulting Image visualization is given below:

[im1.jpg.acj.txt](https://github.com/cherubicXN/anisotropic-scale-junction-detector/files/3915561/im1.jpg.acj.txt)
[im1.jpg.asj.txt](https://github.com/cherubicXN/anisotropic-scale-junction-detector/files/3915562/im1.jpg.asj.txt)


I'm calculating ray segment end point using simple formula:

X = px1 + branch_scale*(cos(branch_angle))
Y = px2 + branch_scale*(sin(branch_angle))

![testJuncOut](https://user-images.githubusercontent.com/25729739/70033687-15d23780-1604-11ea-8052-f2f497c7db37.png)

 Could you please help me in reproducing the image visualization given in paper?

**Comment by cherubicXN** [comment]
Hi,

I just run my code and the results are given in below:

[im1.jpg.asj.txt](https://github.com/cherubicXN/anisotropic-scale-junction-detector/files/3917244/im1.jpg.asj.txt)
[im1.jpg.acj.txt](https://github.com/cherubicXN/anisotropic-scale-junction-detector/files/3917245/im1.jpg.acj.txt)

I found that your result im1.jpg.asj.txt does not contain the anisotropic scales of junctions.

**Comment by asadabbas09** [comment]
Thanks for your reply. I've used your output files and it seems that I can reproduce results given in the paper.

![testJuncOut](https://user-images.githubusercontent.com/25729739/70093643-f9221800-1674-11ea-8aca-b9e24b9900d1.png)

Any idea why my generated files do not contain anisotropic scales of junctions. 

I have tried building everything from scratch but still getting the same results.

**Comment by asadabbas09** [comment]
What I have noticed so far is that `NFA is always > 0 `in the following check-in `aacj.cpp `because `log10((double)Ns) > 2.5` in all cases and probability is very low in the range of `-10-6`

```
NFA = probability + log10((double)Ns);

if (NFA <= 0.0)
{
ret = R;
continue;
}
break;
return MAX(ret, Rlower);
```
Therefore I always get Rlower and branch.scale value remains same as estimated by ACJ.

I'm not sure why my compiled code is behaving like that.

Do you have a compiled binary .exe that I can test out or any local code that I can compile myself?

**Comment by asadabbas09** [comment]
I have changed the following code in `aacj.cpp `in `double AACJDetection::detectAlongTheta` that computes the strength. Because I was getting strength = 0 for all cases. And as a result, was getting a very low probability. Now ASJs estimates are reasonably close to your estimates

```
Strength = 0.0;
		if (!localTheta(iter->x, iter->y, theta, orient, Strength))
			continue;
		//SIN = abs(cos(orient - theta)) - abs(sin(orient - theta));

		//if (SIN <= 0.0)
		//	continue;
		//Strength *= SIN;
		//SIN = fastsin(theta - orient);
		SIN = fastsin(round_pi(orient - theta));
		Strength = Strength*pow2(pow2(1.f-pow2(SIN)));
		strength += Strength;
```

Is that something left by mistake? Can you please have a look in your aacj.cpp file so I can exactly reproduce the results.

My result:
[im1.jpg.asj.txt](https://github.com/cherubicXN/anisotropic-scale-junction-detector/files/3920978/im1.jpg.asj.txt)

**Comment by cherubicXN** [comment]
> What I have noticed so far is that `NFA is always > 0 `in the following check-in `aacj.cpp `because `log10((double)Ns) > 2.5` in all cases and probability is very low in the range of `-10-6`
> 
> ```
> NFA = probability + log10((double)Ns);
> 
> if (NFA <= 0.0)
> {
> ret = R;
> continue;
> }
> break;
> return MAX(ret, Rlower);
> ```
> 
> Therefore I always get Rlower and branch.scale value remains same as estimated by ACJ.
> 
> I'm not sure why my compiled code is behaving like that.
> 
> Do you have a compiled binary .exe that I can test out or any local code that I can compile myself?

The results I uploaded is calculated from the Github version. What's your compiler?

**Comment by asadabbas09** [comment]
Here is my compilation log:

```
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenCV: /usr/local (found version "4.1.0") 
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
./sources/aacj.cpp./sources/aacjout.cpp./sources/acj.cpp./sources/acjpre.cpp./sources/generateSector.cpp./sources/helper.cpp./sources/lsdcall.cpp./sources/main.cpp./sources/nfa.cpp./sources/pdf.cpp
-- Configuring done
-- Generating done

```

**Comment by asadabbas09** [comment]
upgrading gcc and g++ to 6. solved the problem

**Comment by cherubicXN** [comment]
> upgrading gcc and g++ to 6. solved the problem

That's great!
